# 该节点（Minecraft 1.21.1）使用的版本参数
minecraft_version=1.21.1
minecraft_version_range=[1.21.1,1.21.2)
neo_version=21.1.250
neo_version_range=[21.1.0,21.2)
loader_version_range=[4,)
parchment_minecraft_version=1.21.1
parchment_mappings_version=2024.11.17

# 农夫乐事（本模组是其附属）版本
# 可用版本见 https://modrinth.com/mod/farmers-delight/versions
farmersdelight_version=1.21.1-1.3.4
# 写入 neoforge.mods.toml 的依赖版本范围
farmersdelight_version_range=[1.3,)
